### ISSUE TITLE
FindBugs slf4j bug pattern

### ISSUE THREAD

**Issue by maggu2810** [openhab/static-code-analysis#26] opened 2017-03-22 09:05 UTC
IIRC I comment this already on the ESH repo some time ago before the MOJO moved.
Shouldn't the slf4j bug pattern for FindBugs be a mandatory check?
Currently it seems we need to add the pattern in the plugin configuration:
https://github.com/openhab/static-code-analysis/blame/dd38ca38b698189a7e118e6c0adca894b00cedf4/README.md#L41

I assume this should be configured by the plugin itself similar to the FindBugs, Checkstyle, PMD, ... dependencies, too.

**Comment by kaikreuzer** [comment] 2017-03-22 17:46
Is this a duplicate of https://github.com/openhab/static-code-analysis/issues/20?

**Comment by maggu2810** [comment] 2017-03-22 20:25
Didn't think so. Why do you consider that issues as duplicates?

**Comment by kaikreuzer** [comment] 2017-03-22 21:42
Probably because I didn't read it in detail and thought so because of this https://github.com/openhab/static-code-analysis/issues/20#issuecomment-287740007.

**Closed** 2017-06-09 09:03 UTC
Labels: configuration
