### ISSUE TITLE
Runtime failures - transitive dependencies with different versions

### ISSUE THREAD

**Issue by svilenvul** [openhab/static-code-analysis#203] opened 2017-10-06 11:15 UTC
We have experienced several very painful (and hard for diagnostic) problems caused by different versions of dependencies in the runtime classpath:
- https://github.com/openhab/static-code-analysis/issues/180;
- https://github.com/openhab/static-code-analysis/pull/201#issue-261612977;

Most often the build fails with `NoSuchMethodError`, `NoClassDefFoundError` or `ClassNotFoundException`, but it some cases it is wrapped by some other exception (and the real cause remains hidden). E.g. the project is built with commons-io-2.4, but Maven finds commons-io-2.2 in the runtime classpath.

As the build classpath differs from the runtime classpath the problems are unpredictable ... and build dependent, which I think we would like to avoid.

I would like to open this discussion and ask for help/advices , how we could avoid similar problems in the future.

**Comment by svilenvul** [comment] 2017-10-06 11:22
I have started to analyze the dependencies in the project, here I will give some raw data:

[mvn-dependency-tree.txt](https://github.com/openhab/static-code-analysis/files/1362510/mvn-dependency-tree.txt)

And the output of `mvn dependency:analyze`:

```
[INFO] --- maven-dependency-plugin:2.8:analyze (default-cli) @ static-code-analysis ---
Unable to process: org.openhab.tools.analysis.checkstyle.AboutHtmlCheck
Unable to process: org.openhab.tools.analysis.checkstyle.api.AbstractExternalLibrariesCheck
Unable to process: org.openhab.tools.analysis.checkstyle.api.AbstractManifestAttributeCheck
Unable to process: org.openhab.tools.analysis.checkstyle.BuildPropertiesCheck
Unable to process: org.openhab.tools.analysis.checkstyle.ManifestExternalLibrariesCheck
Unable to process: org.openhab.tools.analysis.checkstyle.PackageExportsNameCheck
Unable to process: org.openhab.tools.analysis.checkstyle.RequiredFilesCheck
Unable to process: org.openhab.tools.analysis.tools.AbstractChecker
Unable to process: org.openhab.tools.analysis.utils.CachingHttpClient
Unable to process: org.openhab.tools.analysis.checkstyle.test.AboutHtmlCheckTest
Unable to process: org.openhab.tools.analysis.checkstyle.test.EshInfXmlValidationCheckTest
Unable to process: org.openhab.tools.analysis.utils.CachingHttpClientTest
[WARNING] Used undeclared dependencies found:
[WARNING]    org.apache.commons:commons-lang3:jar:3.4:compile
[WARNING]    org.apache.maven:maven-core:jar:3.0:compile
[WARNING]    net.sourceforge.saxon:saxon:jar:9.1.0.8:compile
[WARNING]    org.eclipse.platform:org.eclipse.equinox.common:jar:3.8.0:compile
[WARNING]    commons-lang:commons-lang:jar:2.6:compile
[WARNING]    xml-apis:xml-apis:jar:1.0.b2:compile
[WARNING]    net.sourceforge.pmd:pmd-core:jar:5.8.1:compile
[WARNING]    org.apache.maven:maven-project:jar:2.2.1:compile
[WARNING]    org.eclipse.platform:org.eclipse.text:jar:3.6.0:compile
[WARNING]    com.google.guava:guava:jar:22.0:compile
[WARNING]    commons-io:commons-io:jar:2.4:compile
[WARNING]    javax.servlet:javax.servlet-api:jar:3.1.0:test
[WARNING]    org.hamcrest:hamcrest-core:jar:1.3:test
[WARNING]    org.apache.maven.shared:maven-shared-utils:jar:0.6:compile
[WARNING]    org.eclipse.platform:org.eclipse.core.filebuffers:jar:3.6.0:compile
[WARNING]    org.eclipse.jetty:jetty-http:jar:9.3.14.v20161028:test
[WARNING]    commons-logging:commons-logging:jar:1.2:compile
[WARNING]    org.codehaus.plexus:plexus-utils:jar:3.0.20:compile
[WARNING]    org.apache.maven:maven-model:jar:3.1.1:compile
[WARNING]    dom4j:dom4j:jar:1.6.1:compile
[WARNING]    backport-util-concurrent:backport-util-concurrent:jar:3.1:compile
[WARNING] Unused declared dependencies found:
[WARNING]    net.sourceforge.pmd:pmd-xml:jar:5.8.1:compile
[WARNING]    org.apache.maven.plugins:maven-plugin-plugin:jar:3.5:compile
[INFO] ------------------------------------------------------------------------
```

**Comment by svilenvul** [comment] 2017-10-06 13:00
I will try to summarize it (please correct me if I am wrong):
- there is a large number of transitive dependencies that are used, but not defined (Apache Commons, Google Guava, dom4j, etc). Until we define them, they are a tick-tacking bomb for runtime issues;
- defining them will pollute the classpath and could cause other failures in the builds where the tool is used (as this was the case with slf4j and ESH);

@kaikreuzer, @martinvw 
What do you think, should we try to package everything into a fat jar and try to isolate them ?

**Comment by kaikreuzer** [comment] 2017-10-06 16:03
I am not an expert on Maven plugin development - the same issue must apply to many other plugins as well, right?
In general, I agree that a plugin must not mess with the classpath for the "regular" projects. So if a fat jar is the only solution to this problem, then be it. But as I said, I don't know if there are any other options and how other plugins deal with that...

**Comment by svilenvul** [comment] 2017-10-13 11:04
> ... the same issue must apply to many other plugins as well, right?

Yes, it seems to be a well known problem, but with no single widely accepted solution :) . I have researched a bit in this field and identified the following options for packaging the dependencies together:
- *maven-dependency-plugin*: The dependency plugin provides the capability to manipulate artifacts. It can **copy and/or unpack artifacts** from local or remote repositories to a specified location;
- *maven-assembly-plugin*: this plugin **extracts all dependency jars into raw classes, and group it together**. Java class name conflicts are possible;
- *maven-shade-plugin*: it packages all dependencies into one uber-jar and to *shade* - i.e. **rename - the packages of some of the dependencies.**

It will be great if someone with experience in using one/several of these approaches can share his opinion.

@kaikreuzer, do you know someone that could help ?

**Comment by lpapazow** [comment] 2018-07-11 13:37
I tried to reproduce an issue similar to [this](https://github.com/eclipse/smarthome/issues/4202#issuecomment-327452627) by building the static-tool with one version of commons-io and adding explicit dependency to another version in another project that includes the static-tool analysis in its goals.

The result was that the project being analysed was able to use a version of commons-io that is different than the one used in the static-tool. 

I assume after #216 was introduced, defining dependencies in the static-tool doesn't break the build if different version of these dependencies are added during the run time.

I would be grateful if anyone could provide a more recent example of such runtime failures.

**Comment by dstivanov** [comment] 2018-07-11 13:56
@kaikreuzer @htreu @maggu2810 Have you recently seen runtime failures concerning `NoSuchMethodError`, `NoClassDefFoundError`, `ClassNotFoundException` ot other dependency issues durint the SAT analysis into the ESH and openHAB builds? 

If not - we can consider that this issues had been resolved by #216 and close it.

**Comment by maggu2810** [comment] 2018-07-11 16:53
What do you mean by "recently"?
IIRC the SAT version has not been changed in ESH for the last month.

**Comment by lpapazow** [comment] 2018-07-11 17:06
@maggu2810 I mean after #216 was merged. 

I read that slf4j was in the list of dependencies, defined in the sat-plugin and there were issues when building smarthome with the tool.

Currently commons-io is included as a dependency but I can't reproduce the issue and I am wondering if #216 solved it.

**Comment by maggu2810** [comment] 2018-07-12 08:23
I don't realized build failures because of SAT, but I see warnings / errors reported in the log of SAT execution (bold red text).
As long as the build succeeds I assume it is not related to this bug.

I don't follow the development here but it seems a lot of changes has been integrated after the release used by ESH has been created. Perhaps we should create a new one some time and have a look at all messages that are caused by the SAT usage.

**Closed** 2021-11-01 18:09 UTC
Labels: enhancement, help wanted
